apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  labels:
    app: sample
  name: sample
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - mountPath: /tmp/
              name: log-dir
          resources:
            limits:
              cpu: 2m
              memory: 1Gi
            requests:
              cpu: 1m
              memory: 100Mi
      volumes:
        - name: log-dir
          emptyDir: {}
